In [156]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Violence Project Mass Shooter Database - Version 6.1.xlsx - Full Database (1).csv

In [157]:
#read in data set with all shooter characteristics
violence=pd.read_csv('/content/drive/My Drive/cleanedShooterData_Apr7.csv')
#violence = violence.set_index('Case #')
print(violence.shape)

(188, 416)

In [158]:
#read in firearm dataset
firearms=pd.read_csv('/content/drive/My Drive/Firearms.csv')

In [159]:
#drop all firearms not used in shooting
firearms = firearms[firearms['Used in Shooting?'] != 0]
firearms = firearms.reset_index()
#fill all missing data with the mode which is zero for all variables
firearms = firearms.fillna(0)
firearms = firearms.drop(columns=['index'])

In [160]:
#this function takes a data set and searches each variable for the max and creates a new data point with the max filled in for each variable
def combine_rows(df):
  c = df['Classification']
  c_list = []
  for i in range(len(c)):
    c_list.append(c[i])
  c = max(c_list)

  ca = df['Caliber']
  ca_list = []
  for i in range(len(ca)):
    ca_list.append(ca[i])
  ca = max(ca)

  m = df['Modified']
  m_list = []
  for i in range(len(m)):
    m_list.append(m[i])
  m = max(m_list)

  lcm = df['Large Capacity Magazine']
  lcm_list = []
  for i in range(len(lcm)):
    lcm_list.append(lcm[i])
  lcm = max(lcm_list)

  em = df['Extended Magazine']
  em_list = []
  for i in range(len(em)):
    em_list.append(em[i])
  em = max(em_list)

  ip = df['Illegal Purchase']
  ip_list = []
  for i in range(len(ip)):
    ip_list.append(ip[i])
  if max(ip_list) > 0:
    ip = 1
  else:
    ip = 0

  data = [[df.iloc[0, 0], df.iloc[0, 1], df.iloc[0, 2], c, ca, m, lcm, em, ip]]
  df = pd.DataFrame(data, columns=['Case #', 'Shooter Last Name', 'Shooter First Name', 'Classification', 'Caliber', 'Modified', 'Large Capacity Magazine', 'Extended Magazine', 'Illegal Purchase'])
  return df

In [161]:
#This function does the same thing as the previous although this one is specifically used for spliting the incidences where multiple shooters where in the same shooting. This creates a copy of each data point or one for each shooter.
def combine_rows_case(df, casenum):
  c = df['Classification']
  c_list = []
  for i in range(len(c)):
    c_list.append(c[i])
  c = max(c_list)

  ca = df['Caliber']
  ca_list = []
  for i in range(len(ca)):
    ca_list.append(ca[i])
  ca = max(ca)

  m = df['Modified']
  m_list = []
  for i in range(len(m)):
    m_list.append(m[i])
  m = max(m_list)

  lcm = df['Large Capacity Magazine']
  lcm_list = []
  for i in range(len(lcm)):
    lcm_list.append(lcm[i])
  lcm = max(lcm_list)

  em = df['Extended Magazine']
  em_list = []
  for i in range(len(em)):
    em_list.append(em[i])
  em = max(em_list)

  ip = df['Illegal Purchase']
  ip_list = []
  for i in range(len(ip)):
    ip_list.append(ip[i])
  if max(ip_list) > 0:
    ip = 1
  else:
    ip = 0

  data = [[casenum, df.iloc[0, 1], df.iloc[0, 2], c, ca, m, lcm, em, ip]]
  df = pd.DataFrame(data, columns=['Case #', 'Shooter Last Name', 'Shooter First Name', 'Classification', 'Caliber', 'Modified', 'Large Capacity Magazine', 'Extended Magazine', 'Illegal Purchase'])
  return df

In [162]:
#start the new data set with the first row
first_row = firearms[firearms['Case #'] == '1']
df = combine_rows(first_row)

In [163]:
#combine rows 2 through 66
sixtysix = df
for i in range(66 - 1):
  char = str(i + 2)
  shooter = firearms[firearms['Case #'] == char]
  shooter = shooter.reset_index()
  shooter = shooter.drop(columns=['index'])
  shooter = combine_rows(shooter)
  sixtysix = pd.concat([sixtysix, shooter])

In [164]:
#split 67 and 68 because there were two shooters at the same shooting
shooter = firearms[firearms['Case #'] == '67, 68']
shooter = shooter.reset_index()
shooter = shooter.drop(columns=['index'])
shooter = combine_rows_case(shooter, '67')
sixtyseven = pd.concat([sixtysix, shooter])

In [165]:
shooter = combine_rows_case(shooter, '68')
sixtyeight = pd.concat([sixtyseven, shooter])

In [166]:
#combine rows 69 through 70
seventy = sixtyeight
for i in range(69, 71):
  char = str(i)
  shooter = firearms[firearms['Case #'] == char]
  shooter = shooter.reset_index()
  shooter = shooter.drop(columns=['index'])
  shooter = combine_rows(shooter)
  seventy = pd.concat([seventy, shooter])

In [167]:
#split 71 and 72 because there were two shooters at the same shooting
seventytwo = seventy
shooter = firearms[firearms['Case #'] == '71, 72']
shooter = shooter.reset_index()
shooter = shooter.drop(columns=['index'])
shooter = combine_rows_case(shooter, '71')
seventyone = pd.concat([seventytwo, shooter])

In [168]:
shooter = combine_rows_case(shooter, '72')
seventytwo = pd.concat([seventyone, shooter])

In [169]:
#combine rows 73 through 141
case_141 = seventytwo
for i in range(73, 142):
  char = str(i)
  shooter = firearms[firearms['Case #'] == char]
  shooter = shooter.reset_index()
  shooter = shooter.drop(columns=['index'])
  shooter = combine_rows(shooter)
  case_141 = pd.concat([case_141, shooter])

In [170]:
#split 142 and 143 because there were two shooters at the same shooting
case_143 = case_141
shooter = firearms[firearms['Case #'] == '142, 143']
shooter = shooter.reset_index()
shooter = shooter.drop(columns=['index'])
shooter = combine_rows_case(shooter, '142')
case_142 = pd.concat([case_143, shooter])

In [171]:
shooter = combine_rows_case(shooter, '143')
case_143 = pd.concat([case_142, shooter])

In [172]:
case_144 = case_143
shooter = firearms[firearms['Case #'] == '144']
shooter = shooter.reset_index()
shooter = shooter.drop(columns=['index'])
shooter = combine_rows(shooter)
case_144 = pd.concat([case_144, shooter])

In [173]:
#combine rows 147 through 171
case_171 = case_144
for i in range(147, 172):
  char = str(i)
  shooter = firearms[firearms['Case #'] == char]
  shooter = shooter.reset_index()
  shooter = shooter.drop(columns=['index'])
  shooter = combine_rows(shooter)
  case_171 = pd.concat([case_171, shooter])

In [174]:
#split 172 and 173 because there were two shooters at the same shooting
case_173 = case_171
shooter = firearms[firearms['Case #'] == '172, 173']
shooter = shooter.reset_index()
shooter = shooter.drop(columns=['index'])
shooter = combine_rows_case(shooter, '172')
case_172 = pd.concat([case_173, shooter])

In [175]:
shooter = combine_rows_case(shooter, '173')
case_173 = pd.concat([case_172, shooter])

In [176]:
#combine rows 174 through 190
case_190 = case_173
for i in range(174, 191):
  char = str(i)
  shooter = firearms[firearms['Case #'] == char]
  shooter = shooter.reset_index()
  shooter = shooter.drop(columns=['index'])
  shooter = combine_rows(shooter)
  case_190 = pd.concat([case_190, shooter])

In [177]:
firearms = case_190

In [178]:
#drop columns we are not doing analysis on
firearms = firearms.drop(columns=['Shooter Last Name', 'Shooter First Name'])

In [179]:
firearms

,Case #,Classification,Caliber,Modified,Large Capacity Magazine,Extended Magazine,Illegal Purchase
0,1,2.0,2.0,0.0,1.0,0.0,0
0,2,0.0,0.0,0.0,0.0,0.0,0
0,3,0.0,2.0,0.0,0.0,0.0,0
0,4,2.0,2.0,0.0,0.0,0.0,0
0,5,2.0,2.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...
0,186,3.0,2.0,0.0,1.0,0.0,0
0,187,2.0,0.0,0.0,1.0,0.0,0
0,188,1.0,0.0,0.0,0.0,0.0,0
0,189,3.0,0.0,0.0,0.0,0.0,0
0,190,0.0,1.0,0.0,0.0,0.0,0

In [180]:
violence['Case #']=violence['Case #'].astype(int)
firearms['Case #']=firearms['Case #'].astype(int)

In [181]:
violence

,Case #,Month,Year,Latitude,Longitude,Insider or Outsider,Workplace Shooting,Multiple Locations,Armed Person on Scene,Family Member Victim,...,Criminal Sentence_1.0.1,Criminal Sentence_2.0.1,Criminal Sentence_3.0.1,Criminal Sentence_4.0.1,Criminal Sentence_5.0.1,Day of Week_Saturday_0,Day of Week_Saturday_1,Pop Culture Connection_0.0,Pop Culture Connection_1.0,Pop Culture Connection_2.0
0,1,8,1966,30.286058,-97.739350,1,0,1,1,1.0,...,0,0,0,0,0,1,0,1,0,0
1,2,11,1966,33.459937,-111.781900,0,0,0,0,0.0,...,1,0,0,0,0,0,1,1,0,0
2,3,10,1967,41.125184,-77.451878,1,1,1,0,0.0,...,0,0,0,0,0,1,0,1,0,0
3,4,3,1968,46.535978,-90.156262,0,0,1,0,0.0,...,0,0,1,0,0,0,1,1,0,0
4,5,4,1969,40.103677,-75.755056,0,0,0,0,0.0,...,0,0,0,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,186,6,2022,36.072814,-95.917624,1,0,0,0,0.0,...,0,0,0,0,0,1,0,1,0,0
184,187,7,2022,42.185853,-87.799210,0,0,0,0,0.0,...,0,0,0,0,0,1,0,0,0,1
185,188,10,2022,35.812595,-78.535545,1,0,1,0,1.0,...,0,0,0,0,0,1,0,0,0,1
186,189,11,2022,38.880978,-104.758104,0,0,0,0,0.0,...,0,0,0,0,0,1,0,1,0,0
187,190,11,2022,36.772622,-76.251284,1,1,0,0,0.0,...,0,0,0,0,0,1,0,1,0,0

In [182]:
firearms

,Case #,Classification,Caliber,Modified,Large Capacity Magazine,Extended Magazine,Illegal Purchase
0,1,2.0,2.0,0.0,1.0,0.0,0
0,2,0.0,0.0,0.0,0.0,0.0,0
0,3,0.0,2.0,0.0,0.0,0.0,0
0,4,2.0,2.0,0.0,0.0,0.0,0
0,5,2.0,2.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...
0,186,3.0,2.0,0.0,1.0,0.0,0
0,187,2.0,0.0,0.0,1.0,0.0,0
0,188,1.0,0.0,0.0,0.0,0.0,0
0,189,3.0,0.0,0.0,0.0,0.0,0
0,190,0.0,1.0,0.0,0.0,0.0,0

In [183]:
#combine shooter dataset with firearms dataset
df = violence.merge(firearms, left_on='Case #', right_on='Case #')

In [184]:
df = df.drop(columns = 'Case #')

In [185]:
df

,Month,Year,Latitude,Longitude,Insider or Outsider,Workplace Shooting,Multiple Locations,Armed Person on Scene,Family Member Victim,Romantic Partner Victim,...,Day of Week_Saturday_1,Pop Culture Connection_0.0,Pop Culture Connection_1.0,Pop Culture Connection_2.0,Classification,Caliber,Modified,Large Capacity Magazine,Extended Magazine,Illegal Purchase
0,8,1966,30.286058,-97.739350,1,0,1,1,1.0,1.0,...,0,1,0,0,2.0,2.0,0.0,1.0,0.0,0
1,11,1966,33.459937,-111.781900,0,0,0,0,0.0,0.0,...,1,1,0,0,0.0,0.0,0.0,0.0,0.0,0
2,10,1967,41.125184,-77.451878,1,1,1,0,0.0,0.0,...,0,1,0,0,0.0,2.0,0.0,0.0,0.0,0
3,3,1968,46.535978,-90.156262,0,0,1,0,0.0,0.0,...,1,1,0,0,2.0,2.0,0.0,0.0,0.0,0
4,4,1969,40.103677,-75.755056,0,0,0,0,0.0,1.0,...,1,1,0,0,2.0,2.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,6,2022,36.072814,-95.917624,1,0,0,0,0.0,0.0,...,0,1,0,0,3.0,2.0,0.0,1.0,0.0,0
184,7,2022,42.185853,-87.799210,0,0,0,0,0.0,0.0,...,0,0,0,1,2.0,0.0,0.0,1.0,0.0,0
185,10,2022,35.812595,-78.535545,1,0,1,0,1.0,0.0,...,0,0,0,1,1.0,0.0,0.0,0.0,0.0,0
186,11,2022,38.880978,-104.758104,0,0,0,0,0.0,0.0,...,0,1,0,0,3.0,0.0,0.0,0.0,0.0,0
187,11,2022,36.772622,-76.251284,1,1,0,0,0.0,0.0,...,0,1,0,0,0.0,1.0,0.0,0.0,0.0,0

In [186]:
#export merged dataset
from pathlib import Path  
filepath = Path('/content/drive/My Drive/Firearms_cleaned_Apr7.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
df.to_csv(filepath)