This notebook begins the cleaning process of our messy dataset as a first pass. The

In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

KeyboardInterrupt: ignored

In [ ]:
import os
os.chdir(r"/content/drive/MyDrive/Econ 484/project/")
filename = 'Violence Project Mass Shooter Database.csv'

### Load and View the Data

In [ ]:
data = pd.read_csv(filename,header=1,index_col=0)

In [ ]:
data

,Shooter Last Name,Shooter First Name,Full Date,Day of Week,Day,Month,Year,Street Number,Street Name,City,...,Interest in Firearms,Firearm Proficiency,Total Firearms Brought to the Scene,Other Weapons or Gear,Specify Other Weapons or Gear,On-Scene Outcome,Who Killed Shooter On Scene,Attempt to Flee,Insanity Defense,Criminal Sentence
Case #,,,,,,,,,,,,,,,,,,,,,
1,Whitman,Charles,8/1/1966,Monday,1,8,1966,110,Inner Campus Dr,Austin,...,1.0,3.0,7.0,1.0,"hatchet, hammer, knives, wrench, ropes, water,...",1.0,2.0,0.0,2.0,0.0
2,Smith,Robert,11/12/1966,Saturday,12,11,1966,Rose-Mar College of Beauty,N Rose,Mesa,...,0.0,1.0,1.0,1.0,"knife, nylon cord",2.0,0.0,0.0,1.0,1.0
3,Held,Leo,10/23/1967,Monday,23,10,1967,599,S Highland St,Lock Haven,...,1.0,3.0,2.0,1.0,holster,1.0,2.0,0.0,2.0,0.0
4,Pearson,Eric,3/16/1968,Saturday,16,3,1968,11703,Lake Rd,Ironwood,...,0.0,0.0,1.0,0.0,NaN,2.0,0.0,0.0,0.0,3.0
5,Lambright,Donald,4/5/1969,Saturday,5,4,1969,NaN,I-76,Harrisburg,...,0.0,3.0,2.0,0.0,NaN,0.0,1.0,0.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,Louis,Michael,6/1/2022,Wednesday,1,6,2022,6161,S Yale Ave,Tulsa,...,0.0,0.0,2.0,0.0,NaN,0.0,1.0,0.0,2.0,0.0
187,Crimo,Robert,7/4/2022,Monday,4,7,2022,NaN,Central Ave,Highland Park,...,1.0,0.0,1.0,0.0,NaN,2.0,0.0,1.0,0.0,NaN
188,Thompson,Austin,10/13/2022,Thursday,13,10,2022,NaN,"Hedingham Suburb, near Osprey Cove Drive and B...",Raleigh,...,NaN,NaN,2.0,1.0,"Camo clothing, backpack, ammo, sheath and hunt...",2.0,0.0,1.0,3.0,NaN
189,Aldrich,Anderson,11/19-20/2022,Saturday/Sunday,19-20,11,2022,3430,N Academy Blvd,Colorado Springs,...,1.0,NaN,2.0,1.0,"military-style flak jacket, additional ammunit...",2.0,0.0,0.0,3.0,NaN
190,Bing,Andre,11/22/2022,Tuesday,22,11,2022,1521,Sam's Cir,Chesapeake,...,0.0,NaN,1.0,1.0,Several additional magazines,0.0,1.0,0.0,2.0,0.0

In [ ]:
for col in data.columns:
  print(col)

Shooter Last Name
Shooter First Name
Full Date
Day of Week
Day
Month
Year
Street Number
Street Name
City
State
County
Zip Code
Latitude
Longitude
State Code
Region
Urban/Suburban/Rural
Metro/Micro Statistical Area Type
Location
Insider or Outsider
Workplace Shooting
Multiple Locations
Other Location
Armed Person on Scene
Specify Armed Person
Number Killed
Number Injured
Family Member Victim
Romantic Partner Victim
Kidnapping or Hostage Situation
Age
Gender
Race
Height
Weight
Immigrant
Sexual Orientation
Religion
Education
School Performance
School Performance Specified
Birth Order
Number of Siblings
Older Siblings
Younger Siblings
Relationship Status
Children
Employment Status
Employment TypeÂ
Military Service
Military Branch
Community Involvement
Community Involvement Specified
Known to Police or FBI
Criminal Record
Part I Crimes
Part II Crimes
Highest Level of Justice System Involvement
History of Physical Altercations
History of Animal Abuse
History of Domestic Abuse
Domestic Abuse Specified
History of Sexual Offenses
Gang Affiliation
Terror Group Affiliation
Known Hate Group or Chat Room Affiliation
Violent Video Games
Bully
Bullied
Raised by Single Parent
Parental Divorce / Separation
Parental Death in Childhood
Parental Suicide
Childhood Trauma
Physically Abused
Sexually Abused
Emotionally Abused
Neglected
Childhood SES
Mother Violent Treatment
Parental Substance Abuse
Parent Criminal Record
Family Member Incarcerated
Adult Trauma
Recent or Ongoing Stressor
Signs of Being in Crisis
Timeline of Signs of Crisis
Signs of Crisis Expanded
Inability to Perform Daily Tasks
Notably Depressed Mood
Unusually Calm or Happy
Rapid Mood Swings
Increased Agitation
Abusive Behavior
Isolation
Losing Touch with Reality
Paranoia
Suicidality
Prior Hospitalization
Voluntary or Involuntary Hospitalization
Prior Counseling
Voluntary or Mandatory Counseling
Psychiatric Medication
Psychiatric Medication Specified
Medication Category
Treatment 6 Months Prior to Shooting
Mental Illness
FASD (Fetal Alcohol Spectrum Disorder)
Known Family Mental Health History
Autism Spectrum
Substance Use
Health Issues
Health Issues - Specify
Head Injury / Possible TBI
Known PrejudicesÂ
Motive: Racism/Xenophobia
Motive: Religious Hate
Motive: Misogyny
Motive: Homophobia
Motive: Employment Issue
Motive: Economic Issue
Motive: Legal Issue
Motive: Relationship Issue
Motive: Interpersonal ConflictÂ
Motive: Fame-Seeking
Motive: OtherÂ
Motive: Unknown
Role of Psychosis in the Shooting
Social Media UseÂ
LeakageÂ
Leakage How
Leakage WhoÂ
Leakage Specific/NonspecificÂ
Interest in Past Mass Violence
Relationship with Other Shooting(s)
Specify Relationship to Other Shooting(s)
Legacy Token
Pop Culture Connection
Specify Pop Culture Connection
Planning
Performance
Interest in Firearms
Firearm Proficiency
Total Firearms Brought to the Scene
Other Weapons or Gear
Specify Other Weapons or Gear
On-Scene Outcome
Who Killed Shooter On Scene
Attempt to Flee
Insanity Defense
Criminal Sentence

# There are many many missing values that we will need to consider

In [ ]:
#Code from Parker that counts how many nulls are in each column
missingVals = data.isnull().sum().sort_values(ascending=False)
print(missingVals[:20]) #Print out columns missing the most data
dropCols = missingVals[missingVals > 15]
notEnoughVals = list(dropCols.index) #Drop all columns that have more than 15 missing values
notEnoughVals

Specify Pop Culture Connection               169
Specify Relationship to Other Shooting(s)    165
Medication Category                          146
Psychiatric Medication Specified             145
Health Issues - Specify                      144
Weight                                       144
Military Branch                              141
Height                                       133
Community Involvement Specified              129
Other Location                               127
Specify Other Weapons or Gear                115
Leakage WhoÂ                                  105
Leakage How                                  104
Leakage Specific/NonspecificÂ                 102
School Performance                           101
School Performance Specified                 100
Religion                                      96
Younger Siblings                              85
Older Siblings                                83
Birth Order                                   80
dtype: int64

['Specify Pop Culture Connection',
 'Specify Relationship to Other Shooting(s)',
 'Medication Category',
 'Psychiatric Medication Specified',
 'Health Issues - Specify',
 'Weight',
 'Military Branch',
 'Height',
 'Community Involvement Specified',
 'Other Location',
 'Specify Other Weapons or Gear',
 'Leakage Who\xa0',
 'Leakage How',
 'Leakage Specific/Nonspecific\xa0',
 'School Performance',
 'School Performance Specified',
 'Religion',
 'Younger Siblings',
 'Older Siblings',
 'Birth Order',
 'Childhood SES',
 'Education',
 'Number of Siblings',
 'Timeline of Signs of Crisis',
 'Employment Type\xa0',
 'Signs of Crisis Expanded',
 'Community Involvement']

### Drop Columns with lots of missing data 
### Drop columns that are strings unrelated/unhelpful to the analysis that can't be made into useful dummies

In [ ]:
#All of these columns are strings that are not relevant to the full dataset. We will drop these.
stringCols = ['Street Number','Street Name','Specify Other Weapons or Gear','County','Shooter First Name','Shooter Last Name','State Code','Full Date','Zip Code','School Performance Specified','Community Involvement','Signs of Crisis Expanded','Psychiatric Medication','Health Issues - Specify','Specify Relationship to Other Shooting(s)','Specify Pop Culture Connection','Who Killed Shooter On Scene','City']

#Combine with the columns with missing data and drop them
dropTheseCols = stringCols + notEnoughVals
dfNew = data.drop(dropTheseCols,axis=1)

print(f"Num Cols: {len(dfNew.columns)}")

Num Cols: 114

In [ ]:
dfNew = pd.get_dummies(dfNew) #We don't need to drop the first column of dummies because there are missing values that won't be made into dummies
dfNew = pd.get_dummies(dfNew,columns=['Location','Children','Criminal Sentence','Highest Level of Justice System Involvement','Known Hate Group or Chat Room Affiliation','Region',
                            'Gender','Relationship Status','History of Domestic Abuse','Violent Video Games','Motive: Religious Hate','Role of Psychosis in the Shooting',
                            'Firearm Proficiency',
                            'On-Scene Outcome',
                            'Insanity Defense',
                            'Urban/Suburban/Rural',
                            'Specify Armed Person',
                            'Military Service',
                            'History of Physical Altercations',
                            'Suicidality',
                            'Voluntary or Involuntary Hospitalization',
                            'Motive: Racism/Xenophobia',
                            dfNew.columns[95],dfNew.columns[98], #This is hardcoded to put in Motive: Other and Social Media Use since the strings weren't working
                            'Pop Culture Connection'])
dfNew.head()

,Month,Year,Latitude,Longitude,Insider or Outsider,Workplace Shooting,Multiple Locations,Armed Person on Scene,Number Killed,Number Injured,...,Criminal Sentence_1.0,Criminal Sentence_2.0,Criminal Sentence_3.0,Criminal Sentence_4.0,Criminal Sentence_5.0,Day of Week_Saturday_0,Day of Week_Saturday_1,Pop Culture Connection_0.0,Pop Culture Connection_1.0,Pop Culture Connection_2.0
Case #,,,,,,,,,,,,,,,,,,,,,
1,8,1966,30.286058,-97.739350,1,0,1,1,15,31,...,0,0,0,0,0,1,0,1,0,0
2,11,1966,33.459937,-111.781900,0,0,0,0,5,2,...,1,0,0,0,0,0,1,1,0,0
3,10,1967,41.125184,-77.451878,1,1,1,0,6,6,...,0,0,0,0,0,1,0,1,0,0
4,3,1968,46.535978,-90.156262,0,0,1,0,7,2,...,0,0,1,0,0,0,1,1,0,0
5,4,1969,40.103677,-75.755056,0,0,0,0,4,17,...,0,0,0,0,0,0,1,1,0,0

### Fill in Missing Values
Now that we've accounted for columns with too many missing values by dropping them, and added in dummy variables, we can fill in the rest of the values with either the mean or the mode.

In [ ]:
#How many are missing
print(dfNew.isnull().sum().sort_values(ascending=False))

def find_mode(column): #This function is from the internet to 
  vals, counts = np.unique (column, return_counts=True)
  index = np.argmax (counts)
  return (vals[index])

missingVals = dfNew.isnull().sum().sort_values(ascending=False)
colsWithNull = missingVals[missingVals > 0].index

#Fill with mean value
for col in colsWithNull:
  print(col)
  if max(dfNew[col]) <= 9: #This should capture any categorical variables we missed in our one-hot encoding
    #Fill with mode
    modeVal = find_mode(dfNew[col].to_numpy()) #Find mode of columns
    dfNew[col] = dfNew[col].fillna(modeVal)

  else:
    #Fill with the mean
    meanVal = np.mean(dfNew[col].to_numpy()) #Find mean of column
    dfNew[col] = dfNew[col].fillna(meanVal)

dfNew.head()

FASD (Fetal Alcohol Spectrum Disorder)    6
Motive: Homophobia                        3
Physically Abused                         3
Motive: Misogyny                          3
Motive: Employment Issue                  3
                                         ..
Part I Crimes_1, 3                        0
Part I Crimes_1, 2, 8                     0
Part I Crimes_1, 2, 3, 4, 5               0
Part I Crimes_1, 2                        0
Pop Culture Connection_2.0                0
Length: 417, dtype: int64
FASD (Fetal Alcohol Spectrum Disorder)
Motive: Homophobia
Physically Abused
Motive: Misogyny
Motive: Employment Issue
Motive: Economic Issue
Motive: Legal Issue
Motive: Relationship Issue
Motive: Interpersonal ConflictÂ
Motive: Fame-Seeking
Motive: OtherÂ
Parental Suicide
Childhood Trauma
Emotionally Abused
Sexually Abused
Parental Divorce / Separation
Neglected
Mother Violent Treatment
Parental Substance Abuse
Parent Criminal Record
Family Member Incarcerated
Parental Death in Childhood
Raised by Single Parent
Prior Counseling
Interest in Firearms
Bully
Sexual Orientation
Bullied
Treatment 6 Months Prior to Shooting
Attempt to Flee
Autism Spectrum
Health Issues
Head Injury / Possible TBI
Other Weapons or Gear
Total Firearms Brought to the Scene
Prior Hospitalization
Performance
Legacy Token
Relationship with Other Shooting(s)
Interest in Past Mass Violence
LeakageÂ
Social Media UseÂ
Motive: Unknown
Planning
Isolation
Paranoia
Terror Group Affiliation
Losing Touch with Reality
Romantic Partner Victim
Age
Immigrant
Known to Police or FBI
History of Animal Abuse
History of Sexual Offenses
Gang Affiliation
Family Member Victim
Signs of Being in Crisis
Notably Depressed Mood
Unusually Calm or Happy
Rapid Mood Swings
Increased Agitation
Abusive Behavior
Inability to Perform Daily Tasks

,Month,Year,Latitude,Longitude,Insider or Outsider,Workplace Shooting,Multiple Locations,Armed Person on Scene,Number Killed,Number Injured,...,Criminal Sentence_1.0,Criminal Sentence_2.0,Criminal Sentence_3.0,Criminal Sentence_4.0,Criminal Sentence_5.0,Day of Week_Saturday_0,Day of Week_Saturday_1,Pop Culture Connection_0.0,Pop Culture Connection_1.0,Pop Culture Connection_2.0
Case #,,,,,,,,,,,,,,,,,,,,,
1,8,1966,30.286058,-97.739350,1,0,1,1,15,31,...,0,0,0,0,0,1,0,1,0,0
2,11,1966,33.459937,-111.781900,0,0,0,0,5,2,...,1,0,0,0,0,0,1,1,0,0
3,10,1967,41.125184,-77.451878,1,1,1,0,6,6,...,0,0,0,0,0,1,0,1,0,0
4,3,1968,46.535978,-90.156262,0,0,1,0,7,2,...,0,0,1,0,0,0,1,1,0,0
5,4,1969,40.103677,-75.755056,0,0,0,0,4,17,...,0,0,0,0,0,0,1,1,0,0

## Now that the data is cleaned, make a y variable or target and drop it from the dataset

In [ ]:
target = dfNew['Number Killed'] + dfNew['Number Injured']
dfNew.drop(['Number Killed', 'Number Injured'],axis=1,inplace=True)

## Check to make sure there are no missing values. Something weird happened that Boston was confused by. So we manually fill these in with mean and mode values respectively

In [ ]:
missingVals = dfNew.isnull().sum().sort_values(ascending=False)[:50]
nullCol = missingVals[missingVals > 0].index
nullCol  #Should be none with nulls, but there are..

Index(['Age', 'Total Firearms Brought to the Scene'], dtype='object')

In [ ]:
meanAge = np.mean(dfNew['Age'])
dfNew['Age'] = dfNew['Age'].fillna(meanAge) #Fill with mean

modeTotal = find_mode(dfNew['Total Firearms Brought to the Scene'].to_numpy()) #Fill with mode
dfNew['Total Firearms Brought to the Scene'] = dfNew['Total Firearms Brought to the Scene'].fillna(modeTotal)

In [ ]:
#Now double check to make sure we got all of the nulls
missingVals = dfNew.isnull().sum().sort_values(ascending=False)[:50]
nullCol = missingVals[missingVals > 0].index
nullCol

Index([], dtype='object')

## Notice something weird in the indexing at 145... 
This is causing issues, so we drop it from the dataset.

In [ ]:
dfNew.iloc[140:148]

,Month,Year,Latitude,Longitude,Insider or Outsider,Workplace Shooting,Multiple Locations,Armed Person on Scene,Number Killed,Number Injured,...,Criminal Sentence_1.0,Criminal Sentence_2.0,Criminal Sentence_3.0,Criminal Sentence_4.0,Criminal Sentence_5.0,Day of Week_Saturday_0,Day of Week_Saturday_1,Pop Culture Connection_0.0,Pop Culture Connection_1.0,Pop Culture Connection_2.0
Case #,,,,,,,,,,,,,,,,,,,,,
141,11,2015,31.835445,-95.838850,1,0,1,0,6,0,...,1,0,0,0,0,0,1,1,0,0
142,12,2015,34.075766,-117.277467,1,1,1,0,14,24,...,0,0,0,0,0,1,0,1,0,0
143,12,2015,34.075766,-117.277467,1,1,1,0,14,24,...,0,0,0,0,0,1,0,1,0,0
144,2,2016,42.235322,-85.677092,0,0,1,0,6,2,...,0,1,0,0,0,0,1,1,0,0
"145, 146",3,2016,40.438200,-79.872920,0,0,0,0,5,3,...,0,0,0,0,0,1,0,0,0,0
147,6,2016,28.519608,-81.376709,0,0,0,0,49,53,...,0,0,0,0,0,1,0,1,0,0
148,7,2016,32.779742,-96.805298,0,0,0,1,5,11,...,0,0,0,0,0,1,0,0,0,1
149,9,2016,48.464723,-122.337055,0,0,0,0,5,0,...,0,0,0,0,0,1,0,1,0,0

In [ ]:
#Drop the weird row from the dataset
dfFinal = dfNew.drop('145, 146')
dfFinal.iloc[140:147]

,Month,Year,Latitude,Longitude,Insider or Outsider,Workplace Shooting,Multiple Locations,Armed Person on Scene,Family Member Victim,Romantic Partner Victim,...,Criminal Sentence_1.0,Criminal Sentence_2.0,Criminal Sentence_3.0,Criminal Sentence_4.0,Criminal Sentence_5.0,Day of Week_Saturday_0,Day of Week_Saturday_1,Pop Culture Connection_0.0,Pop Culture Connection_1.0,Pop Culture Connection_2.0
Case #,,,,,,,,,,,,,,,,,,,,,
141,11,2015,31.835445,-95.838850,1,0,1,0,0.0,0.0,...,1,0,0,0,0,0,1,1,0,0
142,12,2015,34.075766,-117.277467,1,1,1,0,0.0,0.0,...,0,0,0,0,0,1,0,1,0,0
143,12,2015,34.075766,-117.277467,1,1,1,0,0.0,0.0,...,0,0,0,0,0,1,0,1,0,0
144,2,2016,42.235322,-85.677092,0,0,1,0,0.0,0.0,...,0,1,0,0,0,0,1,1,0,0
147,6,2016,28.519608,-81.376709,0,0,0,0,0.0,0.0,...,0,0,0,0,0,1,0,1,0,0
148,7,2016,32.779742,-96.805298,0,0,0,1,0.0,0.0,...,0,0,0,0,0,1,0,0,0,1
149,9,2016,48.464723,-122.337055,0,0,0,0,0.0,0.0,...,0,0,0,0,0,1,0,1,0,0

In [ ]:
#Drop the weird row from the target
targetFinal = target.drop('145, 146')
targetFinal.iloc[140:147]

Case #
141      6
142     38
143     38
144      8
147    102
148     16
149      5
dtype: int64

In [ ]:
#Make sure there is the same number of rows in the target and the dataframe
dfFinal.shape,targetFinal.shape

((188, 415), (188,))

### Save the cleaned dataframe and target

In [ ]:
dfFinal.to_csv('cleanedShooterData_Apr.csv')
targetFinal.to_csv('numInjAndKilled_Apr.csv')

Note that this data is passed to Tom, who merged it with data about the firearms used in each case. This is them to be further analyzed by Hannah.